---
title: "Introdução ao Cálculo Diferencial Integral"
author: "Prof. Wagner Hugo Bonat"
date: '2020'
output: pdf_document
---

```{r, cache=FALSE, include=FALSE}
source("config/setup.R")
```

Exercícios para fixação, recomendo que usem o $\texttt{R}$, $\texttt{python}$ 
e/ou o $\texttt{wxMaxima}$ para auxiliar e verificar suas respostas.

# Funções, limites e continuidade

1. Use o $\texttt{R}$ ou $\texttt{python}$ para desenhar o gráfico das seguintes funções.

a) $f(x) = \sqrt{x}$.
b) $f(x) = \log(x)$.
c) $f(x) = \log_{10}(x)$.
d) $f(x) = \exp(x)$.
e) $f(x) = \Gamma(x)$.
f) $f(x) = \frac{1}{x}$.
g) $f(x) = |x-1| + 2$.
h) $f(x) = beta(x,0.5)$.
i) $f(x) = (x-1)^3$.
j) $f(x) = \frac{x+1}{x}$.

2. Use o $\texttt{R}$ ou $\texttt{python}$ para desenhar o gráfico das seguintes funções.
Identifique o que o parâmetro controla da função. Tenha cuidado com o domínio de cada função.
Note que para estes gráficos o valor de $x$ é uma constante qualquer (pode fixar um número)
e o gráfico é desenhado em relação apenas a $\theta$ o parâmetro da função.

a) $f(x; \theta) = 2 \left (  x \log \frac{x}{\theta} - x + \theta  \right )$.
b) $f(x; \theta) = \binom{100}{x} \exp \left \{ x \log \frac{\theta}{1-\theta} + 100 \log (1 - \theta) \right \}$.
c) $f(x; \theta) = 2\left (  \frac{x}{\theta} - \log \left \{  \frac{x}{\theta} \right \} -1 \right )$.
d) $f(x; \theta, p) = 2\left \{ \frac{x^{(2-p)}}{(1-p)(2-p)} - \frac{x \theta^{(1-p)}}{1-p} + \frac{\theta^{(2-p)}}{2-p} \right \}$.
e) $f(x; \theta, p) = 2\left \{ 1- \cos(x - \theta) \right \}$.

3. Obtenha o limite e esboçe o gráfico.

a) $\lim_{x \to 0 } ( \sqrt{x} + x)$.
b) $\lim_{x \to 2 }  \frac{x^2 + x}{ x + 3}$.
c) $\lim_{x \to 2 }  \frac{x^2 - 4}{ x - 2}$.
d) $\lim_{x \to -1 }  \frac{x^2 - 1}{ x + 1}$.
e) $\lim_{x \to 0}  \sin(x)$.

4. Usando a definição intuitiva de limite esboçe o gráfico das seguintes
funções e avalie se são ou não contínuas.

a) $f(x) = \sqrt{x}$ em $x = 0$.
b) $f(x) = \frac{x^2 - 4}{x-2}$ em $x = 2$.
c) $f(x) = \left\{\begin{matrix}
x \quad \text{se} \quad x < 1 \\ 
\frac{1}{x} \quad \text{se} \quad x > 1 \quad \text{em} \quad x = 1
\end{matrix}\right.$
d) $f(x) = \Gamma(x)$ em $x = 2$.
e) $f(x) = \frac{|x-2|}{x-2}$ em $x = 2$.

# Derivadas

1. Calcule a derivada das seguintes funções:

a) $f(x) = x^4$.
b) $f(x) = x^3$. 
c) $f(x) = x^{-3}$.
d) $f(x) = \frac{1}{x^5}$.
e) $f(x) = \sqrt{x}$.
f) $f(x) = \sqrt[3]{x}$.
g) $f(x) = x^{1/3}$.
h) $f(x) = \frac{1}{x}$.
i) $f(x) = \sqrt[8]{x}$.
j) $f(x) = \frac{1}{x^2}$.

2. Determine a reta tangente ao gráfico de $f(x)$ no ponto requisitado e
esboce o gráfico de $f(x)$ e da reta tangente.

a) $f(x) = \frac{1}{x}$ no ponto de abscissa 2. 
b) $f(x) = x^3$ nos pontos de abscissa -3 e 3. 
c) $f(x) = \exp{x}$ no ponto de abscissa 0. 
d) $f(x) = \log{x}$ no ponto de abscissa 2. 

3. Calcule a derivada das seguintes funções:

a) $f(x) = 4 x^3 + x^2$.
b) $f(x) = 5x^4 + 4$.
c) $f(x) = \frac{2x + 3}{x^2 + 1}$.
d) $f(x) = (3x^2 + 1)\exp^{x}$.
e) $f(x) = \sqrt[3]{x}$.
f) $f(x) = 5 x^4 + 6 x^3 + x^2 + 2$.

4. Calcule a derivada das seguintes funções usando a regra da cadeia.

a) $f(x) = \exp{3x}$.
b) $f(x) = \sin{x^2}$.
c) $f(x) = (3x^2 + 1)^3$.
d) $f(x) = \log{(x^2 + 3)}$.
e) $f(x) = x^2 \exp^{3x}$.
f) $f(x) = \log{(x^2 + 3x + 9)}$.
g) $f(x) = \sqrt{x + \exp^{x}}$.

5. Aproxime as seguintes funções usando a expansão de Taylor de segunda
ordem. Esboce o gráfico da função e da aproximação. Note que $y_i$ é constante
nos valores informados e que a aproximação deve ser feita em relação a $\mu$.
Pode fixar como ponto de referência para a aproximação $\mu_0$ a média dos
$y_i$'s.

a) $\sum_{i=1}^n (y_i - \mu)^2$. Fixe $y_i = 2.09;-1.32;-0.20;0.05;-0.07$.
b) $\sum_{i=1}^n 2 \left ( y_i \log \frac{y_i}{\mu} + \mu - y_i \right )$. 
Fixe $y_i = 7;4;4;6;5$.
c) $\sum_{i=1}^n 2 \left ( \frac{y_i}{\mu} - \log \frac{y_i}{\mu} - 1 \right )$. 
Fixe $y_i = 2.35;0.16;0.56;1.05;0.51$.
d) $\sum_{i=1}^n 2 \left ( y_i \log \frac{y_i}{\mu} + (1- y_i) \log \frac{1-y_i}{1-\mu} \right )$.
Fixe $y_i = 1;0;1;1;1$.
e) $\sum_{i=1}^n 2 \left ( y_i \log \frac{y_i}{\mu} + (m + y_i) \log \frac{m + \mu}{m + y_i} \right)$. Fixe $m = 1$ e $y_i = 7;4;4;6;5$.

6. Considerando as funções apresentadas no exercício 5 identifique o
ponto de inflexão e verique se é um ponto de máximo ou mínimo.

# Integrais

1. Calcule as seguintes integrais indefinidas:

a) $\int x^3 dx$.
b) $\int \frac{1}{x^2} dx$.
c) $\int \sqrt[3]{x^2} dx$.
d) $\int \left ( \frac{1}{x} \right )dx$.
e) $\int \left ( \frac{1}{x} + \sqrt{x} \right )dx$.
f) $\int \exp^{\alpha x} dx$.
g) $\int \exp^{2x} dx$.
h) $\int 3 dx$.
i) $\int \exp^{-x}dx$.
j) $\int (x + 3\exp^{x})dx$.

2. Calcule as seguintes integrais definidas:

a) $\int_{1}^2 x^2 dx$.
b) $\int_{-1}^4 4 dx$.
c) $\int_{0}^2 (x^3 + 3x -1)dx$.
d) $\int_{1}^2 \frac{1}{x^2} dx$.
e) $\int_{1}^2 \left ( \frac{1}{x} + \frac{1}{x^3} \right )dx$.

3. Usando a soma de Riemann (numericamente) calcule as seguintes integrais definidas:

a) $\int_{-150}^{150}\exp^{- \frac{(x - 5)^2}{2}} dx$.
b) $\int_{0}^{100} x \exp^{- \frac{x}{5}} dx$.
c) $\int_{0}^{100} \exp^{- \frac{2(x - 5)^2}{27 x}} dx$.
d) $\int_{0}^{100} \exp^{- \frac{|x-5|}{2}} dx$.
e) $\int_{1}^2 \left ( \frac{1}{x} + \frac{1}{x^3} \right )dx$.

# Aplicações 

1. Sejam $y_i$ valores observados para $i = 1, \ldots, n$. Considere
a função perda absoluta dada por
$$ f(\mu) = \sum_{i=1}^n | y_i - \mu|.$$

a) Usando o $\texttt{R}$ ou qualquer outro software conveniente, simule 
um conjunto de valores adequado para $y_i$.
b) Esboce o gráfico da função perda para este conjunto de dados e diferente valores de $\mu$.
c) Encontre o valor de $\mu$ que miniza a função perda absoluta.
d) Discuta quando a funçao perda absoluta pode ser mais conveniente do que a função perda quadrática.

2. Sejam $y_i$ e $x_i$ valores observados para $i = 1, \ldots, n$. Considere o problema de ajustar uma reta relacionando $y_i$ com $x_i$, usando a função perda absoluta
$$ f(\beta_0,\beta_1) = \sum_{i=1}^n | y_i - (\beta_0 + \beta_1 x_i)|.$$

a) Usando o $\texttt{R}$ ou qualquer outro software conveniente, simule 
um conjunto de valores adequado para $y_i$ fixado um vetor para $x_i$ .
b) Esboce o gráfico da função perda para este conjunto de dados e diferentes valores de $\beta_0$ e $\beta_1$.
c) Encontre o valor de $\beta_0$ e $\beta_1$ que miniza a função perda absoluta.
d) Discuta quando a função perda absoluta pode ser mais conveniente do que a função perda quadrática.